[data]
num_nodes = 300
lag = 48
horizon = 24
val_ratio = 0.2
test_ratio = 0.2
tod = False
normalizer = std
column_wise = False
default_graph = False
add_time_in_day=False
add_day_in_week=False
steps_per_day=24
days_per_week = 7

[model]
input_dim = 1
output_dim = 1
num_layers = 1
feature_hidden_dim = 12
node_emb_dim = 8
num_experts=4
scales=1,3,5,7
contrast_loss_weight=0.3
contrastive_temp=0.1
gamma1=0.1
gamma2=0.1

[train]
loss_func = mae
seed = 12
batch_size = 64
epochs = 100
lr_init = 0.01
weight_decay = 0
lr_decay = True
lr_decay_rate = 0.5
lr_decay_step = 25
early_stop = True
early_stop_patience = 15
grad_norm = False
max_grad_norm = 5
real_value = True

[test]
mae_thresh = None
mape_thresh = 0.

[log]
log_step = 2000
plot = False